

gaussJordan: GaussJordan.C functions.C
	g++ -o gaussJordan GaussJordan.C 
	./gaussJordan

checks: GaussJordan_checks.C
	g++ -o gaussJordan_checks GaussJordan_checks.C
	./gaussJordan_checks

clean:
	rm -f *.x *.o